name: ejtserver

services:
  ejtserver:
    image: crazymax/ejtserver:latest
    container_name: ejtserver
    ports:
      - "11862:11862"
    volumes:
      - "./data:/data"
    env_file:
      - "./ejtserver.env"
    restart: always
