name: test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - '**.md'

env:
  BUILD_TAG: ejtserver:test
  CONTAINER_NAME: ejtserver

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build
        uses: docker/bake-action@v4
        with:
          targets: image-local
        env:
          DEFAULT_TAG: ${{ env.BUILD_TAG }}
      -
        name: Start
        run: |
          docker compose up -d
        working-directory: test
        env:
          EJTSERVER_IMAGE: ${{ env.BUILD_TAG }}
          EJTSERVER_CONTAINER: ${{ env.CONTAINER_NAME }}
          EJT_ACCOUNT_USERNAME: ${{ secrets.EJT_ACCOUNT_USERNAME }}
          EJT_ACCOUNT_PASSWORD: ${{ secrets.EJT_ACCOUNT_PASSWORD }}
          EJTSERVER_LICENSES: ${{ secrets.EJTSERVER_LICENSES }}
      -
        name: Check container logs
        uses: crazy-max/.github/.github/actions/container-logs-check@main
        with:
          container_name: ${{ env.CONTAINER_NAME }}
          log_check: "Service is started"
          timeout: 120
      -
        name: Logs
        if: always()
        run: |
          docker compose logs
        working-directory: test
        env:
          EJTSERVER_IMAGE: ${{ env.BUILD_TAG }}
          EJTSERVER_CONTAINER: ${{ env.CONTAINER_NAME }}
